# Generated by Django 4.2 on 2023-04-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CollectAll', '0002_collection_collector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='Collector',
            new_name='CollectMember',
        ),
    ]
